// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZG6-sWXB7yG7tV9cm8hOQVOtHXEtdKeI',
    appId: '1:515209796030:web:018d1af6b0cd2659ed81ef',
    messagingSenderId: '515209796030',
    projectId: 'ipssi112023',
    authDomain: 'ipssi112023.firebaseapp.com',
    storageBucket: 'ipssi112023.appspot.com',
    measurementId: 'G-WJP2YR344F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmOhlaxsdd4MbF14C7RL_8mqiI8EX8wyQ',
    appId: '1:515209796030:android:e9a74b87b06d1156ed81ef',
    messagingSenderId: '515209796030',
    projectId: 'ipssi112023',
    storageBucket: 'ipssi112023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6BkB1wU7YKNSLks6WwltJlNsNUhcCUAc',
    appId: '1:515209796030:ios:eaf32de50f12607eed81ef',
    messagingSenderId: '515209796030',
    projectId: 'ipssi112023',
    storageBucket: 'ipssi112023.appspot.com',
    iosBundleId: 'com.example.isspiBd3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6BkB1wU7YKNSLks6WwltJlNsNUhcCUAc',
    appId: '1:515209796030:ios:2edd3236c94ae62aed81ef',
    messagingSenderId: '515209796030',
    projectId: 'ipssi112023',
    storageBucket: 'ipssi112023.appspot.com',
    iosBundleId: 'com.example.isspiBd3.RunnerTests',
  );
}
